version: '3'

services:
  tad:
    image: postgres
    container_name: 'postgres'
    environment:
      - POSTGRES_DB=telos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    ports:
      - 5432:5432
